Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/Refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),

]

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/adopcion/urls.py
from django.urls import include, path


from apps.adopcion.views import index_adopcion

app_name = 'apps'
urlpatterns = [
    path('index', index_adopcion),
 ]

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete
from apps.mascota.views import	MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete


app_name = "mascota"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eliminar'),

]

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/adopcion/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=70)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=12)
	email = models.EmailField()
	domicilio = models.TextField()


	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona


class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)


class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/adopcion/forms.py
# -*- encoding:utf-8 -*-
from django import forms

from apps.adopcion.models import Persona, Solicitud



class PersonaForm(forms.ModelForm):

	class Meta:
		model = Persona
		fields = [
			'nombre',
			'apellidos',
			'edad',
			'telefono',
			'email',
			'domicilio',
		]
		labels = {
			'nombre': 'Nombre',
			'apellidos': 'Apellidos',
			'edad': 'Edad',
			'telefono': 'Teléfono',
			'email': 'Correo electrónico',
			'domicilio': 'Domicilio',
		}
		widgets = {
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'apellidos':forms.TextInput(attrs={'class':'form-control'}),
			'edad':forms.TextInput(attrs={'class':'form-control'}),
			'telefono':forms.TextInput(attrs={'class':'form-control'}),
			'email':forms.TextInput(attrs={'class':'form-control'}),
			'domicilio':forms.Textarea(attrs={'class':'form-control'}),
		}


class SolicitudForm(forms.ModelForm):

	class Meta:
		model = Solicitud
		fields = [
			'numero_mascotas',
			'razones',	
		]
		labels = {
			'numero_mascotas': 'Numero de mascotas',
			'razones': 'Razones para adoptar',
			
		}
		widgets = {
			'numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
			'razones':forms.Textarea(attrs={'class':'form-control'}),
		}

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota


class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]
		labels = {
			'nombre': 'Nombre',
			'sexo': 'Sexo',
			'edad_aproximada': 'Edad aproximada',
			'fecha_rescate':'Fecha de rescate',
			'persona': 'Adoptante',
			'vacuna': 'Vacunas',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'sexo': forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			'vacuna': forms.CheckboxSelectMultiple(),
		}

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect



def index_adopcion(request):
	return HttpResponse("soy la pagina principal de la app adopcion")

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota


def index(request):
	return render(request, 'mascota/index.html')


def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()
	return render(request, 'mascota/mascota_form.html', {'form':form})


def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id')
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)



def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html', {'form':form})



def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})


class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
	paginate_by = 2

class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')


class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')


class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
				                        </ul>
		                      		</li>
			                       
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://codigofacilito.com" onclick="pageTracker._link(this.href); return false;">Código Facilito</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/base/header.html
<header>Hola</header>

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title%}
Mascota
{% endblock %}


{% block content %}
<h1>Contenido de la aplicación mascota</h1>
{% endblock%}

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>	
	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class= "btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>
{% endblock %}

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}

	<button type="submit">Guardar</button>
</form>
{% endblock %}

Progra lll/Ambientes/lol19/ProyectosDjango/Refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha de Rescate</td>
			<td>Vacunas</td>
			<td>Adoptante</td>
			<td>Acciones</td>
			<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
				<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
			</td>
			

		</tr>
		
	</thead>
	<tbody>
		{% if object_list %}
		{% for mascota in object_list %}
		<tr>
			<td>{{ mascota.id }}</td>
			<td>{{ mascota.nombre }}</td>
			<td>{{ mascota.sexo }}</td>
			<td>{{ mascota.edad_aproximada }}</td>
			<td>{{ mascota.fecha_rescate }}</td>
			<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>	
		</tr>
		<td>
		    <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
			<a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
			</td>
		{% endfor %}
		
		{% else %}

		<h1>No hay registros de mascotas</h1>
		{% endif %}
	</tbody>
</table> 

{% endblock%}